### ISSUE TITLE
Conflict with SDWebImage (ARC version)

### ISSUE THREAD

**Issue by kuldeepkod** [mwaterfall/MWPhotoBrowser#127]
My project needs to use SDWebmage (ARC) and MWPhotBrowser (non ARC). This causes a conflict and due to that get and error in MWPhoto.h (Semantic error: Cannot find protocol declaration for SDWebImageDecoderDelegate).
Maybe the renaming of SDWebImage under MWPhotoBrowser project would resolve this?

SDWebImage from:
https://github.com/rs/SDWebImage

MWPhotoBrowser from:
https://github.com/mwaterfall/MWPhotoBrowser

**Comment by shinto-shintzz** [comment]
Still the issues is there

**Comment by snehageorge** [comment]
Ya getting the same issue even now.
