### ISSUE TITLE
weird scrolling issue

### ISSUE THREAD

**Issue by eito** [mwaterfall/MWPhotoBrowser#142]
I'm seeing a weird issue in the app I'm currently working on and I notice the same issue in the demo app from this repo. To repro:
- Go into the Flickr photo section
- scroll all the way to the last image
- try to scroll back one image, it bounces back, then scrolling again successfully scrolls the image

In the app I'm working on, images in the album are downloaded from a URL. When an image has yet to download, I can scroll to it just fine and see the progress indicator, but if that image has already been loaded, I see the same "scroll right/left-scroll back to original place" behavior. 

NOTE: I see this in the simulator and device

**Comment by ruchi45** [comment]
Want to load more images as scroll reaches end. But I cant find scrolled event of PhotoBrowser.
