### ISSUE TITLE
Make jumpToPageAtIndex:animated: public method

### ISSUE THREAD

**Issue by ghost** [mwaterfall/MWPhotoBrowser#158]
I'm not sure if this is the best method to use, but it would be nice to animate index changes rather than jumping between them as currently with setCurrentPhotoIndex.

**Comment by RyanKim01** [comment]
Can you show me a use case of showNextPhotoAnimated and showPreviousPhotoAnimated:? I'm not sure how to implement this code. I was calling on my browser like "browser.showPreviousPhotoAnimated:" Thank you in advance

**Comment by skarctop** [comment]
But still have problem, how to know when is grid or single show.   if  grid, can be single photo after click collectioncell. 
hope add a bool  to show current show style
