### ISSUE TITLE
Add support for videos

### ISSUE THREAD

**Issue by mwaterfall** [mwaterfall/MWPhotoBrowser#182]

**Comment by esusatyo** [comment]
@mwaterfall Have you considered accepting this pull request? https://github.com/mwaterfall/MWPhotoBrowser/pull/316

**Comment by koszcz** [comment]
+1

**Comment by marinotws** [comment]
:+1:

**Comment by mwaterfall** [comment]
Good news, video support is here!

I'll be pushing the new version spec to Cocoapods at some point today but feel free to take it for a spin. Still need to get videos working with the old asset library URLs but that shouldn't take long. It currently works great with `PHAsset` objects or URLs to videos.

**Comment by mwaterfall** [comment]
All done, v2.1.0 is live!
