### ISSUE TITLE
Grid view Done button just dismiss the grid

### ISSUE THREAD

**Issue by MaxHasADHD** [mwaterfall/MWPhotoBrowser#226]
Its kind of confusing for the done button to dismiss the whole photo browser in grid view. Would be better to just dismiss the grid to the last image shown

**Comment by wdcurry** [comment]
if i may inquire: i find the workflow of a modal presentation flipping from grid to single pic view to be confusing with respect to the Done button. Logic dictates that a button does exactly what it suggests. In this case, this is not true. I commented out the block to return logic to the Done button:
````
//        if (self.enableGrid) {
//            if (self.startOnGrid && !_gridController) {
//                [self showGrid:YES];
//                return;
//            } else if (!self.startOnGrid && _gridController) {
//                [self hideGrid];
//                return;
//            }
//        }
````
