### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by venkatchm** [mwaterfall/MWPhotoBrowser#268]
I am creating an gallery to hold both photo & video. MWPhotoBrowser works well for Photo. But not supporting  video. is there anyway to support video ?

**Comment by mwaterfall** [comment]
Dupe of #182

**Comment by kedardesai** [comment]
I am creating an gallery to hold both photo & video. MWPhotoBrowser works well for Photo. But not working for videos. It opens video but unable to show. Even time frame appers as --:-- I guess video is unable to download or run. Video I am trying to show is from youtube. Please help.
