### ISSUE TITLE
Parse issue Missing '@end', Semantic issue Missing context for method declaration etc.

### ISSUE THREAD

**Issue by isayeter** [mwaterfall/MWPhotoBrowser#270]
Hi,

When I try to integrate this class to my project via copying all files to my project, it gives these 4 errors.

![screen shot 2014-06-17 at 5 37 00 pm](https://cloud.githubusercontent.com/assets/3602109/3301694/bdcf89d0-f62d-11e3-9843-3fdfd1317373.png)

What can be the problem ? 

Note: I'm using iOS 8 SDK

**Comment by LargeShrimp** [comment]
I also meet this issue,how to resolve this.

**Comment by jndefosse** [comment]
Move this line to the top : 

#import <objc/runtime.h>

**Comment by LargeShrimp** [comment]
ok,thanks! And i resolve it with update PSTCollectionView。
