### ISSUE TITLE
How to hide status bar in navigation bar?

### ISSUE THREAD

**Issue by Pozitive23** [mwaterfall/MWPhotoBrowser#342]
In my code, status bar is hidden,but after show that component, status bar will appear...

**Comment by vikmeup** [comment]
@Pozitive23  Subclass MWPhotoBrowser and then override prefersStatusBarHidden to hide or show status bar
```objective-c
- (BOOL)prefersStatusBarHidden
{
    return true;
}
```

**Comment by mwaterfall** [comment]
If you always hide the status bar then you can set `View controller-based status bar appearance` to `YES` in your info.plist and then select "Hide status bar" in your target's general tab. Otherwise, yes subclassing would be the other option.
