### ISSUE TITLE
Status bar is black

### ISSUE THREAD

**Issue by MaxHasADHD** [mwaterfall/MWPhotoBrowser#354]
The status bar needs to be white on a dark navigation bar.

**Comment by vikmeup** [comment]
@MaxHasADHD Subclass MWPhotoBrowser and then override method: 
UIStatusBarStyleLightContent or UIStatusBarStyleDefault (Black)
```objective-c
- (UIStatusBarStyle)preferredStatusBarStyle
{
    return UIStatusBarStyleLightContent;
}
```

**Comment by mwaterfall** [comment]
This is now sorted.
