### ISSUE TITLE
Photo load external database

### ISSUE THREAD

**Issue by marinotws** [mwaterfall/MWPhotoBrowser#358]
I use load image from local and from query from external database, the responses from the database from the internet are asyncrone and I can not get the picture immediately be assigned to MWPhoto ... is possible you can later assign to the image es. photo [anIndex].image = [UIImage imageWithContentsOfFile:localFilePath]; and then at PhotoBrowser.reloadData ??

thanks

**Comment by mythodeia** [comment]
@maritotws
you can add the MWPhoto when you get the replies from your server and then load the gallery or call the reloadData of the MWPhotoBrowser

**Comment by marinotws** [comment]
Hi mythodeia,ok reloadData for MWPhotoBrowser but if i am in the grid (reload data o refresh grid) ?

**Comment by mythodeia** [comment]
i think the reload data covers the grid as well.

**Comment by marinotws** [comment]
mmm no i see the image counter increases but does not update the grid

**Comment by mythodeia** [comment]
does this help you?
https://github.com/mwaterfall/MWPhotoBrowser/pull/328

**Comment by marinotws** [comment]
ohhh Yes !! thank you !
