### ISSUE TITLE
reload Single Photo 

### ISSUE THREAD

**Issue by marinotws** [mwaterfall/MWPhotoBrowser#364]
Any ideas on reloading a single photo (in grid) without using the reloadData ?? 

thanks.

**Comment by mythodeia** [comment]
if you know the indexpath then you could use the ```[self.collectionView reloadItemsAtIndexPaths:@[your_item's_indexpath]] ```

**Comment by marinotws** [comment]
@mythodeia thanks but collectionview (_gridController.collectionView) is private ??

**Comment by mythodeia** [comment]
i know but in order to be able to reload specific item you either expose it as public or write a custom public helper method that will internally reload that specific item.

**Comment by marinotws** [comment]
ja @mythodeia the problem is the index since they are asynchronous calls ....
