### ISSUE TITLE
memory warning ..

### ISSUE THREAD

**Issue by marinotws** [mwaterfall/MWPhotoBrowser#365]
Hi, i have 200 photo in MWPhotoBrowser (2/3 MB for one photo), if i navigate quickly between images received memory warning and if i do not close the view the app crash ....

**Comment by fparkar** [comment]
If you have 2-3 MB one photo then you have to think on your design. Try to resize the photos only decrease the size...

**Comment by marinotws** [comment]
ok. thanks
