### ISSUE TITLE
Could not build Objective-C module 'MWPhotoBrowser'

### ISSUE THREAD

**Issue by mirzadelic** [mwaterfall/MWPhotoBrowser#386]
I imported in my controller:
```
import UIKit
import SwiftyJSON
import MWPhotoBrowser
```
but i get error on MWPhotoBrowser:
```
Could not build Objective-C module 'MWPhotoBrowser'
```

How can i solve this?

**Comment by chainone** [comment]
I met the same problem

**Comment by Miracle-lau** [comment]
same to you! how did u solve it?

**Comment by nobunobu** [comment]
Up

**Comment by mwaterfall** [comment]
This is now fixed in the new version that I have just pushed up. You should now be able to `import MWPhotoBrowser` within Swift correctly (as long as you are building your pods as frameworks).

**Comment by grubino** [comment]
I'm getting this error in xcode 7 with the following Podfile:

```
workspace 'Luzene.xcworkspace'
use_frameworks!

target 'Luzene' do
        ....
        pod "MWPhotoBrowser"
end
```

What am I doing wrong?
