### ISSUE TITLE
Enable Modules (C and Objective-C)

### ISSUE THREAD

**Issue by goktugaral** [mwaterfall/MWPhotoBrowser#397]
Hi there,

In my "Build Settings", there is a "Enable Modules (C and Objective-C)" and it was chosen as "No". 
I have to use another open source library for something else and the only way for use it, is to set  "Enable Modules (C and Objective-C)" as "Yes".

When I run the project, some error occurred.

Under the MWPhotoBrowser/Libraries..

- PSTCollectionViewLayout.m where #pragma mark - PSTCollection/UICollection interoperability
//Missing context for method declaration.

- PSTCollectionView.m where line 2283

CGFloat PSTSimulatorAnimationDragCoefficient(void) {
    static CGFloat (*UIAnimationDragCoefficient)(void) = NULL;
#if TARGET_IPHONE_SIMULATOR
#import <dlfcn.h>
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        UIAnimationDragCoefficient = (CGFloat (*)(void))dlsym(RTLD_DEFAULT, "UIAnimationDragCoefficient");
    });
#endif
    return UIAnimationDragCoefficient ? UIAnimationDragCoefficient() : 1.f;
}

Could you give me some urgent advice? Thank you.

**Comment by mwaterfall** [comment]
Are you able to install it using Cocoapods? That should separate your app's config from this project's config.
