### ISSUE TITLE
A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs

### ISSUE THREAD

**Issue by fparkar** [mwaterfall/MWPhotoBrowser#399]
When I open your code in iOS8.3, I get below error.

2015-05-25 15:21:54.325 MyAppName[70750:9764502] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:]: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109b67c65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001097cebb7 objc_exception_throw + 45
	2   CoreFoundation                      0x0000000109b67b9d +[NSException raise:format:] + 205
	3   Foundation                          0x00000001094f6233 VerifyConstraintArguments + 219
	4   Foundation                          0x000000010935fa5a +[NSLayoutConstraint constraintWithItem:attribute:relatedBy:toItem:attribute:multiplier:constant:] + 427
	5   MyAppName                               0x0000000108d564c3 +[RMPickerViewController dismissDateSelectionViewController:fromViewController:] + 419
	6   MyAppName                               0x0000000108d5bb9c -[RMPickerViewController dismiss] + 92
	7   MyAppName                               0x0000000108d3b112 -[NewsDetailsViewController details_ImageAction:] + 50
	8   MyAppName                               0x0000000108d3ab6c -[NewsDetailsViewController connectionDidFinishLoading:] + 1644
	9   CFNetwork                           0x000000010eb5c0bc __65-[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:]_block_invoke + 69
	10  CFNetwork                           0x000000010eb5c060 -[NSURLConnectionInternal _withConnectionAndDelegate:onlyActive:] + 199
	11  CFNetwork                           0x000000010eb5c1c7 -[NSURLConnectionInternal _withActiveConnectionAndDelegate:] + 48
	12  CFNetwork                           0x000000010ea2b757 ___ZN27URLConnectionClient_Classic26_delegate_didFinishLoadingEU13block_pointerFvvE_block_invoke + 107
	13  CFNetwork                           0x000000010eaf8de1 ___ZN27URLConnectionClient_Classic18_withDelegateAsyncEPKcU13block_pointerFvP16_CFURLConnectionPK33CFURLConnectionClientCurrent_VMaxE_block_invoke_2 + 273
	14  CFNetwork                           0x000000010ea16a26 _ZN19RunloopBlockContext13_invoke_blockEPKvPv + 72
	15  CoreFoundation                      0x0000000109a6e354 CFArrayApplyFunction + 68
	16  CFNetwork                           0x000000010ea168e7 _ZN19RunloopBlockContext7performEv + 133
	17  CFNetwork                           0x000000010ea16726 _ZN17MultiplexerSource7performEv + 256
	18  CFNetwork                           0x000000010ea1653c _ZN17MultiplexerSource8_performEPv + 72
	19  CoreFoundation                      0x0000000109a9b431 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	20  CoreFoundation                      0x0000000109a912fd __CFRunLoopDoSources0 + 269
	21  CoreFoundation                      0x0000000109a90934 __CFRunLoopRun + 868
	22  CoreFoundation                      0x0000000109a90366 CFRunLoopRunSpecific + 470
	23  GraphicsServices                    0x000000010bd4ca3e GSEventRunModal + 161
	24  UIKit                               0x000000010a9f2900 UIApplicationMain + 1282
	25  MyAppName                               0x0000000108e13c03 main + 99
	26  libdyld.dylib                       0x000000010fb56145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Any reason why?

**Comment by mwaterfall** [comment]
This issue seems to be coming from RMPickerViewController not MWPhotoBrowser.
