### ISSUE TITLE
Using with Swift

### ISSUE THREAD

**Issue by mndhkr** [mwaterfall/MWPhotoBrowser#403]
I can't use this with swift.
I don't know why, but Xcode does not ask me for a bridging header, and no class from MWPhotoBrowser is seen by Xcode in Swift...
What i need to do?
Thank you :-)

**Comment by mwaterfall** [comment]
I'll be pushing a new version of the browser that fixes Swift support with frameworks so you can now `import MWPhotoBrowser` correctly. If you are building your pods as static libraries then you will need to create the bridging header and `#import "MWPhotoBrowser.h"` from there to make that API accessible in Swift.
