### ISSUE TITLE
Change default status bar style

### ISSUE THREAD

**Issue by walsh2000** [mwaterfall/MWPhotoBrowser#405]
Related to #354, but your solution is not possible:

When UIViewControllerBasedStatusBarAppearance is 0, MWPhotoBrowser uses UIStatusBarStyleDefault, but I believe UIStatusBarStyleLightContent looks better.

I'm going to submit a pull request for this tiny one-liner. I hope you'll consider taking it.

<img width="607" alt="screen shot 2015-07-06 at 12 00 52 pm" src="https://cloud.githubusercontent.com/assets/4912283/8530701/59f102e4-23d7-11e5-9f75-d0a19aabb71a.png">

**Comment by walsh2000** [comment]
PR #406

**Comment by mwaterfall** [comment]
Thanks, I'll get that incorporated now!
