### ISSUE TITLE
mwphotocaption - action - uiactiviyviewcontroller

### ISSUE THREAD

**Issue by hjanuschka** [mwaterfall/MWPhotoBrowser#417]
hello

first of all - i am using mwphotobrowser for along time, in almost all projects where i need to display galleries or sort of - just loving it :)

right now i want to add a few buttons in the mwphotocaption - managed to do so.
one of the buttons should show uiactiviyviewcontroller.

adding a addTarget on the button inside the mwphotocaption subclass would run following code:

    UIActivityViewController *activityViewController =
        [[UIActivityViewController alloc] initWithActivityItems:@[string, URL, mtl.image.image]
                                          applicationActivities:nil];
        [self.navigationController presentViewController:activityViewController
                                                animated:YES
                                              completion:^{
                                                  NSLog(@"SHARED");
                                              }];

problem is that i don't have a reference to self.navigationcontroller? - how do i get the navigation controller from the currently presented photobrowser (presented modally)

regards
helmut

**Comment by hjanuschka** [comment]
ok workaround - subclass mwphoto, and set an ivar for the navigationcontroller via the delegate

**Comment by paoloboschini** [comment]
Hi hjanuschka, did you mean MWCaptionView instead of mwphotocaption?

A question: how did you manage to get click events from buttons in a MWCaptionView?
I added a button in my MWCaptionView subclass but the action attached to the button is never called.

Example:

        let button = UIButton.buttonWithType(UIButtonType.System) as! UIButton
        button.frame = CGRect(x: 10, y: 30, width: 50, height: 20)
        button.setTitle("tap", forState: UIControlState.Normal)
        button.setTitleColor(UIColor.whiteColor().colorWithAlphaComponent(0.8), forState: UIControlState.Normal)
        button.addTarget(self, action: "tap", forControlEvents: UIControlEvents.TouchUpInside)
        addSubview(button)

Thanks for your support

**Comment by hjanuschka** [comment]
@paoloboschini  - see the gist: https://gist.github.com/hjanuschka/bfd81cab92eed5598d2c (obj-c sample)

i guess the most common error is - that by default the mwphotocaptionview has userinteraction disabled.


to enable it:

    - (void)setupCaption {
        self.userInteractionEnabled=YES;
     }
