### ISSUE TITLE
could you please provide any suggestion on display videos like the Photo app?

### ISSUE THREAD

**Issue by edmundsu** [mwaterfall/MWPhotoBrowser#42]
this project helped me a lot and saved me tons of time, thanks a lot, and this is much better than Three20!!

i got a problem here, is there any way to display videos like the native Photo app does in the scrollview?

I just need some suggestions, you don't have to provide me sample code. wish i could get some ideas for this, because i am stucked at this for a weeks already.

thanks

**Comment by mwaterfall** [comment]
Dupe of #182
