### ISSUE TITLE
How to get the UIImage out of MWPhoto?

### ISSUE THREAD

**Issue by drussu** [mwaterfall/MWPhotoBrowser#421]
I've been poking around for a while, and I can't seem to find a way to simply get the UIImage out of a MWPhoto object. 

Is there a way to do this? Or will I have to add a getter for that myself? 

I need to be able to do this because I need to be able to check if two MWPhoto objects are equal... but there is not a way to do that, so I figure I can compare their images instead.

**Comment by jiangyancong** [comment]
Do you use MWPhotoBrowser as a Image Picker or a Browser? Normally, as a photo browser, we will pass a photo list to the browser to display, we could init MWPhoto by below methods.

- (id)initWithImage:(UIImage *)image;
- (id)initWithURL:(NSURL *)url;

So we could access the image through NSURL or UIImage directly, depends on which init method you use.
you could refer to MWPhoto.m.
```
@interface MWPhoto () {
@property (nonatomic, strong) UIImage *image;
@property (nonatomic, strong) NSURL *photoURL;
////
@end

@implementation MWPhoto

@synthesize underlyingImage = _underlyingImage; // synth property from protocol
```

**Comment by drussu** [comment]
But that doesn't really address the issue... why is the image property of an MWPhoto object private? There should be a way to easily get an image/video URL out of an MWPhoto object.

**Comment by jiangyancong** [comment]
Then you could just make it public or write a getter method.
In the version(V1.4.1) I'm using, the image property is in MWPhoto.h.

**Comment by drussu** [comment]
Ah, I see, so the UIImage property of MWPhoto objects was explicitly made private in the latest version. I will make it public, in that case. Thanks for your help!
