### ISSUE TITLE
what I shoud return for this if im using swift? MWPhotoProtocol

### ISSUE THREAD

**Issue by alexliubj** [mwaterfall/MWPhotoBrowser#425]
func photoBrowser(photoBrowser: MWPhotoBrowser!, photoAtIndex index: UInt) -> MWPhotoProtocol!
    {
        if (index < UInt(self.photos.count)) {
            return self.photos[index]
        }
        return nil;
    }

**Comment by alexliubj** [comment]
im using this one now:

 if Int(index) < self.photos.count {
            return photos[Int(index)] as MWPhoto
        }
        
        return nil

**Comment by alexliubj** [comment]
Its works.

**Comment by parthibl** [comment]
@alexliubj thank you! , it works.
