### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by tapz** [mwaterfall/MWPhotoBrowser#432]
Would really like to get rid of all iOS 8 warnings...

Instead of checking the interface orientation you should check if width is greater than height and consider that landscape. In iOS 9 several apps may be visible at the same time and app's size may be anything regardless of the device orientation.

Also changing UIBarMetricsLandscapePhone to UIBarMetricsCompact should just be a find-replace operation. With this, half of the warnings would be gone.

**Comment by novinfard** [comment]
These warnings are really annoying, how to remove them?
