### ISSUE TITLE
Xcode 7 compiler warning on MWPhotoBrower.m

### ISSUE THREAD

**Issue by peng90** [mwaterfall/MWPhotoBrowser#436]
Xcode 7 GM warning:
```
MWPhotoBrowser.m:550:1: Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')
```

**Comment by Aashays-whichit** [comment]
Hey,

Were you able to resolve this warning?

**Comment by Alkalouti** [comment]
Hey all change it with this code
#if __IPHONE_OS_VERSION_MAX_ALLOWED < __IPHONE_9_0
#define supportedInterfaceOrientationsReturnType NSUInteger
#else
#define supportedInterfaceOrientationsReturnType UIInterfaceOrientationMask
#endif

- (supportedInterfaceOrientationsReturnType)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskAll;
}

**Comment by peng90** [comment]
I tried Alkalouti's solution and the warning is gone.
