### ISSUE TITLE
Any idea how to change or add Album Source for Case 9 Photos and Videos Locally?

### ISSUE THREAD

**Issue by glennposadas** [mwaterfall/MWPhotoBrowser#442]
I'm sorry if this is not really an issue, I've been studying your sample project for 2 days now. Fortunately, I have successfully learned how to present MWPhotoBrowser, but I need to select other Album Source. 

Do I have to edit: #pragma mark - Load Assets?
or just inside the Case: 9 code? Please tell me!

**Comment by sovianisa** [comment]
same here, have you find any solution to change album source? it will be very help full thank you

**Comment by glennposadas** [comment]
Hi annisa. I posted the question on Github last year when I was still new
in iOS. Right now, I am using PHAssets and not ALAssets. Thus I didnt use
mwphotobrowser.
