### ISSUE TITLE
warnings with xcode 7.0.1

### ISSUE THREAD

**Issue by TomMajor** [mwaterfall/MWPhotoBrowser#448]
I get 17 warnings overall with xcode 7.0.1 in MWGridViewController.m and MWPhotoBrowser.m:

7x  'interfaceOrientation' is deprecated: first deprecated in iOS 8.0

8x  'UIBarMetricsLandscapePhone' is deprecated: first deprecated in iOS 8.0 - Use UIBarMetricsCompact instead

1x  'setCompletionHandler:' is deprecated: first deprecated in iOS 8.0 - Use completionWithItemsHandler instead.

1x  Conflicting return type in implementation of 'supportedInterfaceOrientations': 'UIInterfaceOrientationMask' (aka 'enum UIInterfaceOrientationMask') vs 'NSUInteger' (aka 'unsigned long')

---

project builds ok, most of them are just "deprecated" warnings but would be nice if these could be fixed sometime anyway, who knows what will happen when the next iOS version arrives :)
And it's kind of ugly to have 17 yellow exclamation marks in the project.

Thanks,
Tom

**Comment by Sean-Wang** [comment]
![image](https://cloud.githubusercontent.com/assets/1193073/10474685/3c2ac414-726c-11e5-921e-027733e88d88.png)

Please fix.

**Comment by fdddf** [comment]
+1

**Comment by marinotws** [comment]
+1

**Comment by ded** [comment]
I've got 18 warnings. But they're understandable during this time. It's tough to keep support for iOS7 and not have these warnings. Btw, the adoption rate has been skyrocketing https://mixpanel.com/trends/#report/ios_9/

**Comment by dimohamdy** [comment]
+1

**Comment by sstadtl** [comment]
+1

**Comment by LinkedHK** [comment]
Seems like this repo has been abandoned . Someone would have create a fork and push maintenance updates there.

**Comment by novinfard** [comment]
+1

**Comment by novinfard** [comment]
By changing these 2 files, all warnings will disappear. Wonder why the project didn't update.

[MWGridViewController.m.zip](https://github.com/mwaterfall/MWPhotoBrowser/files/131111/MWGridViewController.m.zip)

[MWPhotoBrowser.m.zip](https://github.com/mwaterfall/MWPhotoBrowser/files/131099/MWPhotoBrowser.m.zip)

**Comment by TomMajor** [comment]
With the latest commits by Michael and the new version 2.1.2, the problem is resolved. Thanks!
