### ISSUE TITLE
How to change nav title colour?And when you look at the long picture,how to show it like this beginning?

### ISSUE THREAD

**Issue by ClegeJJ** [mwaterfall/MWPhotoBrowser#452]
![Uploading iOS Simulator Screen Shot 2015年10月20日 上午9.38.36.png…]()
![Uploading iOS Simulator Screen Shot 2015年10月20日 上午9.39.20.png…]()

**Comment by carsten-wenderdel** [comment]
Concerning your first question - in our app we do it with:
`[UINavigationBar appearance].titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor company_blue_1]};`

If you want to change it for the photo browser only, you might want to edit `MWPhotoBrowser.m`. Look at the methods `setNavBarAppearance`, `storePreviousNavBarAppearance` and `restorePreviousNavBarAppearance`.

I had a similar issue; I wanted to remove the title color previously set with the line above in this comment. This is how I did it. Pay attention to set it back properly:
https://github.com/mwaterfall/MWPhotoBrowser/issues/290
https://github.com/carsten-wenderdel/MWPhotoBrowser/commit/aec112ec030abc464a1ba395a07899332e9f99b3

**Comment by ClegeJJ** [comment]
Thank you for helping me finish solving the first problem;

**Comment by ClegeJJ** [comment]
When i look at the long-photos 
![ios simulator screen shot 2015 10 22 10 02 36](https://cloud.githubusercontent.com/assets/13790283/10670368/c5f114d0-7917-11e5-803d-bc59e5faf0f5.png)

but,I want  stretch it and make pic on the top, 

how to make it??
