### ISSUE TITLE
UIImage underlyingImage

### ISSUE THREAD

**Issue by badalpub1991** [mwaterfall/MWPhotoBrowser#465]
I am getting this error :

'NSInvalidArgumentException', reason: '-[UIImage underlyingImage]: unrecognized selector sent to instance 0x7fa688c96040'
I have used all things correctly but still i am getting this error. what is the issue ?

Here is my code:

  NSInteger ind = indexPath.item;
    
    //_customcell.collectiondeletebtn.tag=indexPath.row;
    
    indexo=ind;
    indexPath=[arrayOfImages objectAtIndex:indexPath.row];
    
    
    MWPhotoBrowser *browser = [[MWPhotoBrowser alloc] initWithDelegate:self];
    browser.displayActionButton = NO;
    browser.displayNavArrows = YES;
    //browser.displaySelectionButtons = displaySelectionButtons;
    //browser.alwaysShowControls = displaySelectionButtons;
    browser.zoomPhotosToFill = YES;
    //browser.enableGrid = enableGrid;
    //browser.startOnGrid = startOnGrid;
    browser.enableSwipeToDismiss = NO;
    browser.autoPlayOnAppear = autoPlayOnAppear;
    [browser setCurrentPhotoIndex:ind];
    MWPhoto *photo;

    [self.navigationController pushViewController:browser animated:YES];

#pragma mark - MWPhotoBrowserDelegate

     - (NSUInteger)numberOfPhotosInPhotoBrowser:(MWPhotoBrowser *)photoBrowser {
       return arrayOfImages.count;
     }
    - (id <MWPhoto>)photoBrowser:(MWPhotoBrowser *)photoBrowser photoAtIndex:(NSUInteger)index {
      if (index < arrayOfImages.count)
        return [arrayOfImages objectAtIndex:indexo];
      return nil;
   }

**Comment by MourinhoLove** [comment]
I have same problem.Can you tall me How to fix this.
