### ISSUE TITLE
Implement Delete Functionality 

### ISSUE THREAD

**Issue by badalpub1991** [mwaterfall/MWPhotoBrowser#466]
Hi ! thank you for this awesome control. I want to know that have you implement delete functionality in this model ? And if i want to add custom buttom at bottom bar and implement delete function how can i achive this ? is it possible ?
Thank you.

**Comment by badalpub1991** [comment]
I have Done Setup Like This,
--------MWPhotoBrowserPrivate.h----------

Create deleted Button Object in MWPhotoBrowserPrivate.h:
            UIBarButtonItem *_deleteButton;

--------MWPhotoBrowser.h----------
Then Created Delegate Method For Delete Button in MWPhotoBrowser.h 
        - (void)photoBrowser:(MWPhotoBrowser *)photoBrowser deletebuttonPressedforPhotoAtIndex:(NSUInteger)index  ;

--------MWPhotoBrowser.m----------

Then Setup it in Viewdidload Method of MWPhotoBrowser.m :
            _deleteButton=[[UIBarButtonItem alloc]initWithBarButtonSystemItem:UIBarButtonSystemItemTrash target:self action:@selector(deletePhoto:)];

Add This item to Perform Layout Method of MWPhotoBrowser.m :
               if (_previousButton && _nextButton ) {
        hasItems = YES;
        
       [items addObject:_deleteButton];
        [items addObject:flexSpace];
        [items addObject:_previousButton];
        [items addObject:flexSpace];
        [items addObject:_nextButton];
        [items addObject:flexSpace];
        [items addObject:flexSpace];

      }

Then Declare Action in MWPhotoBrowser.m :
        - (void)deletePhoto:(id)sender {
    
    
     id <MWPhoto> photo = [self photoAtIndex:_currentPageIndex];
    
     if ([self.delegate respondsToSelector:@selector(photoBrowser:deletebuttonPressedforPhotoAtIndex:)]) {
        
        [self.delegate photoBrowser:self deletebuttonPressedforPhotoAtIndex:_currentPageIndex];
        [self reloadData];
       }
    
     }

--------Menu.m----------
And Finally Setup it in Menu.m Viewcontroller :
    
      - (void)photoBrowser:(MWPhotoBrowser *)photoBrowser deletebuttonPressedforPhotoAtIndex:(NSUInteger)index
   {
    NSLog(@"Image Will Be delete at Index%lu",(unsigned long)index);
    [_photos removeObjectAtIndex:index];
    
    }

**Comment by agmo-ios** [comment]
@badalpub1991 Hi, how to add a pop up alert to get confirmation from user while delete button is pressed?

**Comment by badalpub1991** [comment]
@agmo-ios. you can configure your popup in this method .  ``` - (void)photoBrowser:(MWPhotoBrowser *)photoBrowser deletebuttonPressedforPhotoAtIndex:(NSUInteger)index```
