### ISSUE TITLE
getting the current image in scrollview

### ISSUE THREAD

**Issue by tolgatanriverdi** [mwaterfall/MWPhotoBrowser#56]
Hello
It would be nice to have a method which will return the currently showing image on scrollview
I've tried some way to manipulate it (You can see it in below) but no luck because as far as I understand when I check the current underlying image property its returning the next image(according to direction of scrolling)

This is the method I've added to MWPhoto class:

-(UIImage*) getImagePtr
{
    return self.underlyingImage;
}

This is the mwphotobrowser delegate:

-(MWPhoto*)photoBrowser:(MWPhotoBrowser *)photoBrowser photoAtIndex:(NSUInteger)index
{
    if (index < [self.photos count]) {
        MWPhoto *currentPhoto = [self.photos objectAtIndex:index];
        currentNoteImage = currentPhoto.getImagePtr;
        return currentPhoto;
    }
    return nil;
}

**Comment by badalpub1991** [comment]
Any solution related to this issue ?
