### ISSUE TITLE
MBProgressHUD 最新正式版已经是1.0.0了，你这个库里面的依赖能不能升级一下？

### ISSUE THREAD

**Issue by brave723** [mwaterfall/MWPhotoBrowser#587]
MBProgressHUD 最新正式版已经是1.0.0了，你这个库里面的依赖能不能升级一下？

**Comment by biggercoffee** [comment]
同+1，其他库的依赖和这个库的依赖MBProgressHUD，版本不一样，报错了。

**Comment by y500** [comment]
升级MBProgressHUD到1.0.0，SDWebImage到4.0.0，使用方法:

pod "MWPhotoBrowser", :podspec =>'https://raw.githubusercontent.com/y500/MWPhotoBrowser/master/MWPhotoBrowser.podspec'

只能帮你到这里了

**Comment by younatics** [comment]
See [MediaBrowser](https://github.com/younatics/MediaBrowser) I made this library to Swift3 using latest SDWebImage
