### ISSUE TITLE
Adding to the toolbar

### ISSUE THREAD

**Issue by lvthunder** [mwaterfall/MWPhotoBrowser#60]
What is the best way to add to the toolbar.  I like how you can change the MWCaptionView.  Can you add something like that for the toolbar or do I just need to subclass MWPhotoBrowser to do it.  What I want to do is add a button to add to favorites.

**Comment by ehmadzubair** [comment]
did you find a way to do this @Gman9855 @lvthunder

**Comment by lvthunder** [comment]
No I never did it.
