### ISSUE TITLE
Showing space on Top

### ISSUE THREAD

**Issue by HamentM** [mwaterfall/MWPhotoBrowser#623]
Hi, I am facing this issue with **multiple photo grid** in iOS 11, its showing space on top 
![img_0154](https://user-images.githubusercontent.com/25785860/32403820-a8f04c06-c169-11e7-87dd-ef5af6fb3878.PNG)
![img_0155](https://user-images.githubusercontent.com/25785860/32403822-a9552d7e-c169-11e7-83e6-e94e3f85ee0b.PNG)
![img_0156](https://user-images.githubusercontent.com/25785860/32403823-a99e1098-c169-11e7-9178-fec9a3fb6d8b.PNG)

when I come first. This space is continuously increasing if we click on any image and then came back. For more reference Please find the attachment. Any quick help, please.

**Comment by patelmayank** [comment]
@HamentM  Have you fix it ?

**Comment by aherrick** [comment]
I'm seeing this as well. Is there a fix or work around?
