### ISSUE TITLE
when i first open this photoBrowser, problem like this pic , how can i fix it???

### ISSUE THREAD

**Issue by snaillovesmile** [mwaterfall/MWPhotoBrowser#634]
![img_08e982344e24-1](https://user-images.githubusercontent.com/33648940/39510137-2e57b1ca-4e1b-11e8-8c3c-5d11491b72e6.jpeg)

**Comment by sidslog** [comment]
@SnailLoveSmile How did you fix it?

**Comment by snaillovesmile** [comment]
the video picture when you cliped was not a right frame, you can see this field
